execute if score "event randomizer" game matches 0 run scoreboard players random "event randomizer" game 1 52
execute if score "event randomizer" game matches 1 if score "E1" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 2 if score "E2" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 3 if score "E3" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 4 if score "E4" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 5 if score "E5" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 6 if score "E6" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 7 if score "E7" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 8 if score "E8" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 9 if score "E9" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 10 if score "E10" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 11 if score "E11" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 12 if score "E12" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 13 if score "E13" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 14 if score "E14" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 15 if score "E15" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 16 if score "E16" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 17 if score "E17" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 18 if score "E18" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 19 if score "E19" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 20 if score "E20" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 21 if score "E21" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 22 if score "E22" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 23 if score "E23" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 24 if score "E24" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 25 if score "E25" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 26 if score "E26" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 27 if score "E27" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 28 if score "E28" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 29 if score "E29" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 30 if score "E30" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 31 if score "E31" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 32 if score "E32" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 33 if score "E33" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 34 if score "E34" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 35 if score "E35" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 36 if score "E36" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 37 if score "E37" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 38 if score "E38" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 39 if score "E39" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 40 if score "E40" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 41 if score "E41" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 42 if score "E42" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 43 if score "E43" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 44 if score "E44" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 45 if score "E45" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 46 if score "E46" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 47 if score "E47" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 48 if score "E48" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 49 if score "E49" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 50 if score "E50" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 51 if score "E51" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 52 if score "E52" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 53 if score "E53" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 54 if score "E54" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 55 if score "E55" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 56 if score "E56" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 57 if score "E57" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 58 if score "E58" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 59 if score "E59" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 60 if score "E60" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 61 if score "E61" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 62 if score "E62" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 63 if score "E63" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 64 if score "E64" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 65 if score "E65" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 66 if score "E66" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 67 if score "E67" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 68 if score "E68" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 69 if score "E69" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 70 if score "E70" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 71 if score "E71" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 72 if score "E72" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 73 if score "E73" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 74 if score "E74" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 75 if score "E75" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 76 if score "E76" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 77 if score "E77" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 78 if score "E78" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 79 if score "E79" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 80 if score "E80" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 81 if score "E81" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 82 if score "E82" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 83 if score "E83" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 84 if score "E84" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 85 if score "E85" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 86 if score "E86" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 87 if score "E87" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 88 if score "E88" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 89 if score "E89" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 90 if score "E90" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 91 if score "E91" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 92 if score "E92" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 93 if score "E93" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 94 if score "E94" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 95 if score "E95" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 96 if score "E96" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 97 if score "E97" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 98 if score "E98" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 99 if score "E99" events matches 1 run scoreboard players set "event randomizer" game 0
execute if score "event randomizer" game matches 100 if score "E100" events matches 1 run scoreboard players set "event randomizer" game 0
# = end =
execute unless score "event randomizer" game matches 0 if score timer game matches 0 run function game_functions/event_randomizer/event_announcer
execute unless score "event randomizer" game matches 0 if score timer game matches 0 run scoreboard players remove timer game 1
execute if score timer game matches ..-40 run function game_functions/event_run
execute if score timer game matches ..-40 unless score gamemode game matches 1..2 run scoreboard players set timer game 80
execute if score timer game matches ..-40 if score gamemode game matches 1 run scoreboard players set timer game 10
execute if score timer game matches ..-40 if score gamemode game matches 2 run scoreboard players set timer game 20
