execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run gamemode adventure @s
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run effect @s clear
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run hud @s reset all
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run camera @s clear
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run inputpermission set @s movement enabled
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run inputpermission set @s camera enabled
execute as @a[tag=lobby, tag=game] at @s if block ~ ~-2 ~ brr:spawn run scoreboard players remove players game 1
execute as @a[tag=lobby, tag=game] at @s if block ~ ~-2 ~ brr:spawn run clear @s
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove game
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove shop
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove spectator
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house1
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house2
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house3
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house4
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house5
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house6
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house7
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house8
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house9
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house10
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house11
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove house12
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv2
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv3
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv4
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv5
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv6
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv7
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv8
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv9
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv10
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv11
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv12
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv13
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv14
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv15
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv16
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv17
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv18
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv19
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove inv20
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove chill
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove subspace1
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove subspace
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove blackhole1
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove blackhole
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove innocent
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove murderer
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove 1minute
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove miner
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove game_ring
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove speed
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove duel1
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove duel2
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove jump
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove health
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove flashbang
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove vote_winner
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove blast
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove assassin
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target1
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target2
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target3
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target4
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target5
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target6
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target7
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target8
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target9
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target10
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target11
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target12
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target13
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target14
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target15
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target16
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target17
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target18
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target19
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target20
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove target21
execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove invisible

execute as @a[tag=lobby] at @s if block ~ ~-2 ~ brr:spawn run tag @s remove lightbulb

execute as @a[tag=lover] at @s run tag @s add tag_lover
execute as @a[tag=lover] at @s run tag @s add tag_lover1
execute as @a[tag=lover] at @s run tag @s remove lover
