# normal rotation
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=1}] at @s run structure load E11E3M1 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=3}] at @s run structure load E11E3M2 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=5}] at @s run structure load E11E3M3 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=7}] at @s run structure load E11E3M4 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=9}] at @s run structure load E11E3M5 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=11}] at @s run structure load E11E3M6 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=13}] at @s run structure load E11E3M7 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=15}] at @s run structure load E11E3M8 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=17}] at @s run structure load E11E3M9 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=19}] at @s run structure load E11E3M10 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=21}] at @s run structure load E11E3M11 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=23}] at @s run structure load E11E3M12 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=25}] at @s run structure load E11E3M13 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=27}] at @s run structure load E11E3M14 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=29}] at @s run structure load E11E3M15 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=31}] at @s run structure load E11E3M16 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=33}] at @s run structure load E11E3M17 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=35}] at @s run structure load E11E3M18 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=37}] at @s run structure load E11E3M19 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=39}] at @s run structure load E11E3M20 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=41}] at @s run structure load E11E3M21 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=43}] at @s run structure load E11E3M22 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=45}] at @s run structure load E11E3M23 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=47}] at @s run structure load E11E3M24 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=49}] at @s run structure load E11E3M25 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=51}] at @s run structure load E11E3M26 ~-3 ~ ~-3
execute as @s[type=brr:plate, tag=ufo, scores={rotation=0, "ufo animation"=53}] at @s run structure load E11E3M27 ~-3 ~ ~-3
# rotation 90_degrees