# Add whoever it is you don't want to see play this map here. just write "kick <the player's username> (the reason is optional)"
kick FireSlice322 "banned for exploiting"
kick rxqel "banned for exploiting"
kick SmetankaStefani "banned for exploiting"
kick Biasedcoyote437 "banned for exploiting"
kick miedork3 "banned for exploiting"
kick kloscall12 "banned for exploiting"
kick TatusGamer1526 "banned for exploiting"
kick BedrockPlr "banned for flooding the chat"
kick tricky_career3 "banned for disrespecting the developer and thinking they know anything about game development"
kick ProBark74252879 "banned for ruining the peace in the lobby and accusing players of hacking"
kick "Blud -_-" "banned for self promotion and flooding the chat"
kick "Conmic lon" "banned for flooding the chat"
kick GardenWool84230 "banned cuz gay"
kick Lloydsuper5407 "banned for being immature"
kick "noah .c" "banned for being a niggerr"
kick StormyRain16 "banned for exploiting"
kick Dinoluke7865 "banned for swearing"
kick DChris702 "banned for predatory behaviour. this is a federal crime with 5-25 years in prison."
kick Viking9388 "banned for begging non stop every day"
kick Valentin20233 "banned for exploiting"
kick DieguitoMC7770 "banned for exploiting"
#kick niceninjapro "banned for disrespecting the developer"
kick RedDragon4052 "banned for exploiting"
kick GAL4KTIX "go play something else if it's boring"
kick ItsFoxxay "banned for using invisible skins"
kick bacon0408 "suck a niggga dick"
kick Kingston9412 "banned for exploiting"
kick XtobyX32 "banned for exploiting"
#kick "The ending4836" "banned for spamming and acting childish"
kick kalum "go to bed lil niggga"
kick AphmauAaron6803 "banned for exploiting"
kick Jackb770 "banned for exploiting"
kick BraydenRayden "banned for being toxic, unreasonably aggressive and sending death threats to fellow members of the community. this is actually illegal and could get you in jail for years"
#kick tokaimaru "banned for being unserious and overall annoying"
kick BraydenRayden "banned for being unserious and overall annoying"
kick NotSneakyXD "banned for exploiting"
kick Zac10284 "banned for server bombing"
kick TensiveYT "banned from any BRR produced experience"
kick jackb779 "banned for exploiting"
kick "K3V0101" "banned for referencing nsfw"
#kick SMlestops5836 "banned for exploiting"
kick "cocoa pebbIez" "banned for vulgar language"
kick LJewel14 "banned from any BRR produced experience"
kick Firetstyfrnd "banned for spamming"
kick SirRobertDino "banned for existing"
kick Bigyeeter1029 "banned for sexual comments and vulgar behaviour"