# scores
scoreboard players add sweeper gamemodes 1
# murder
execute as @e[type=brr:laser_entity] at @s positioned ^-25 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-24 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-23 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-22 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-21 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-20 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-19 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-18 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-17 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-16 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-15 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-14 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-13 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-12 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-11 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-10 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-9 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-8 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-7 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-6 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-5 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-4 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-3 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-2 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^-1 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^ ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^1 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^2 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^3 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^4 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^5 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^6 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^7 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^8 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^9 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^10 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^11 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^12 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^13 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^14 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^15 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^16 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^17 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^18 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^19 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^20 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^21 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^22 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^23 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^24 ^ ^ run kill @a[tag=game, r=0.5]
execute as @e[type=brr:laser_entity] at @s positioned ^25 ^ ^ run kill @a[tag=game, r=0.5]
# spin
execute as @e[type=brr:laser_entity] at @s positioned ~ ~ ~ run tp @s ~ ~ ~ facing @e[type=brr:plate, name=sweeper]
# plate spin
execute as @e[type=brr:plate, name=sweeper] at @s positioned ^ ^ ^ if score "sweeper speed" gamemodes matches 1 run tp @s ^-1 ^ ^ facing @e[type=brr:laser_entity]
execute as @e[type=brr:plate, name=sweeper] at @s positioned ^ ^ ^ if score "sweeper speed" gamemodes matches 2 run tp @s ^-2 ^ ^ facing @e[type=brr:laser_entity]
execute as @e[type=brr:plate, name=sweeper] at @s positioned ^ ^ ^ if score "sweeper speed" gamemodes matches 3 run tp @s ^-3 ^ ^ facing @e[type=brr:laser_entity]
execute as @e[type=brr:plate, name=sweeper] at @s positioned ^ ^ ^ if score "sweeper speed" gamemodes matches 4 run tp @s ^-4 ^ ^ facing @e[type=brr:laser_entity]
# speed up
execute if score gamemode game matches 11 if score sweeper gamemodes matches 1 run scoreboard players set "sweeper speed" events 1
execute if score gamemode game matches 11 if score sweeper gamemodes matches 500 run scoreboard players set "sweeper speed" events 2
execute if score gamemode game matches 11 if score sweeper gamemodes matches 1000 run scoreboard players set "sweeper speed" events 3
execute if score gamemode game matches 11 if score sweeper gamemodes matches 2000 run scoreboard players set "sweeper speed" events 4